"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import appReducer from "@/statemanagement/appReducer";
import { init } from "@/statemanagement/init";
import { useReducer } from "react";
const inter = Inter({ subsets: ["latin"] });
import { Provider } from "@/statemanagement/appContext";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [state, dispatch] = useReducer(appReducer, init);
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*  2. Provide the data to the context 
        <Provider value={{ state, dispatch }}> // short hand syntax
          {children}
        </Provider>
        // or use the below approach.
        */}
        <Provider value={{ state: state, dispatch: dispatch }}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
